<?php
// $Id$

/**
 * Implements hook_field_info().
 */
function imfield_field_info() {
  return array(
    'icq' => array(
      'label' => t('ICQ Field'),
      'description' => t('This field stores an ICQ number'),
      'default_widget' => 'icq_textfield',
      'default_formatter' => 'icq_onlinestatus',
    ),
  );
}

/**
 * Implements hook_field_is_empty().
 */
function imfield_field_is_empty($item, $field) {
  return empty($item['value']);
}

/**
 * Implements hook_field_formatter_info().
 */
function imfield_field_formatter_info() {
  return array(
    'icq_onlinestatus' => array(
      'label' => t('Onlinestatus'),
      'field types' => array('icq'),
    ),
    'icq_unformatted' => array(
      'label' => t('Unformatted'),
      'field types' => array('icq'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function imfield_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  
  switch ($display['type']) {
    case 'icq_onlinestatus':
      foreach ($items as $delta => $item) {
        $output = $item['value'];
        if($output) {
          // TODO: Make themable
          $output = "<img src=\"http://status.icq.com/online.gif?icq={$output}&img=5\" />" . $output;
        }
        $element[$delta] = array('#markup' => $output);
      }
      break;
    
    case 'icq_unformatted':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => $item['value']);
      }
      break;
  }
  
  return $element;
}

/**
 * Implements hook_field_widget_info().
 */
function imfield_field_widget_info() {
  return array(
    'icq_textfield' => array(
      'label' => t('Text field'),
      'field types' => array('icq'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 */
function imfield_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['value']) ? $items[$delta]['value'] : '';
  
  $element += array(
    '#type' => 'textfield',
    '#default_value' => $value,
  );
  
  $element['#element_validate'][] = 'icqfield_field_widget_validate';
  
  return array('value' => $element);
}

/**
 * Implements hook_field_validate().
 */
function imfield_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // TODO: Find out what makes a valid ICQ number.
  // Also look at icqfield_field_widget_validate
}

/**
 * FAPI validation of an individual icq element.
 */
function imfield_field_widget_validate($element, &$form_state) {
  $value = $element['#value'];
  
  if (!empty($value)) {
    $value = trim($value);
    
    if (!preg_match('/^[0-9]{1,10}$/', $value)) {
      form_error($element, t('The ICQ number is not valid.'));
    }
    else {
      form_set_value($element, $value, $form_state);
    }
  }
}

/**
 * Implements hook_field_widget_error().
 */
function imfield_field_widget_error($element, $error, $form, &$form_state) {
  form_error($element['value'], $error['message']);
}
